#!/usr/bin/env bash
printf "~ a r s e n a l ~\nloading...\n"
SELF=`realpath $0`
BASE=`dirname $SELF`
TMUX="tmux -f $BASE/tmux.conf"
COMMAND="$TMUX attach || $TMUX"
SHELL="$BASE/shell.nix"
nix-shell $@ --command "$COMMAND" "$SHELL"
