#!/usr/bin/env bash
COMMAND="tmux -f tmux.conf attach || tmux -f tmux.conf"
SHELL="$(dirname $(realpath $0))/shell.nix"
printf "~ a r s e n a l ~\nloading...\n"
nix-shell $@ --command "$COMMAND" "$SHELL"
